global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mkt'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Docker
    scrape_interval: 5s
    metrics_path: '/metrics'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      