# Generated by Django 5.2.1 on 2025-05-26 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('debug', 'Debug'), ('info', 'Information'), ('success', 'Success'), ('custom', 'Custom')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type'], name='monitoring__event_t_990929_idx'), models.Index(fields=['source'], name='monitoring__source_8b8f11_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_41fd59_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Metric name', max_length=100)),
                ('value', models.FloatField(help_text='Metric value')),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measurement', max_length=20)),
                ('labels', models.JSONField(blank=True, default=dict, help_text='Metric labels')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name', 'timestamp'], name='monitoring__name_a1566d_idx')],
            },
        ),
    ]
